AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Egress IP Detector - AWS Lambda

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs20.x

Resources:
  DetectEgressIPFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: .
      Description: Detect Lambda function egress IP addresses
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
